### ISSUE TITLE
Flacon will not recognize very large .flac files (1,8gb or more)

### ISSUE THREAD

**Issue by JungleJim42** [flacon/flacon#165]
Hi! Thanks for this great software!

I have been able to successfully split many albums with Flacon. However, when I try to split very large Flac files (1,8gb or more, 5.1 surround mixes), Flacon will open the .cue file, list the tracks, but will not load the flac file (white cross in red box). When I try to manually add the flac file (with the small three dots), I get a "the file is corrupted or not supported" error message.

I have tried both the 7 and 8 version of Flacon on Ubuntu. I also tried the Flatpak.

Thanks for any help

**Comment by SokoloffA** [comment]
I have not tested a program with such large files. I will try to generate such a file and split it. 
For the best result, give me more information:
1. Audio-file parameters. Please post the output of one of the following commands:  
```mediainfo YOUR_BIG_AUDIO_FILE```
```ffmpeg -i  YOUR_BIG_AUDIO_FILE```
2. Send me the CUE file.

**Comment by JungleJim42** [comment]
Here is the mediainfo:
General
Complete name                            : James Guthrie Surround Mix (2003).flac
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
File size                                : 2.55 GiB
Duration                                 : 43 min 25 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 8 421 kb/s

Audio
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Duration                                 : 43 min 25 s
Bit rate mode                            : Variable
Bit rate                                 : 8 421 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 96.0 kHz
Bit depth                                : 24 bits
Compression mode                         : Lossless
Stream size                              : 2.55 GiB (100%)
Writing library                          : libFLAC 1.2.1 (UTC 2007-09-17)


Here is the ffmpeg -i output:

ffmpeg -i "James Guthrie Surround Mix (2003).flac"
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, flac, from 'James Guthrie Surround Mix (2003).flac':
  Metadata:
    VALID_BITS      : 24
    HDCD            : 0
  Duration: 00:43:25.44, start: 0.000000, bitrate: 8420 kb/s
    Stream #0:0: Audio: flac, 96000 Hz, 5.1(side), s32 (24 bit)

**Comment by JungleJim42** [comment]
I don't know how to send you the .cue file. I could just copy it in a forum post.

**Comment by SokoloffA** [comment]
> I don't know how to send you the .cue file. I could just copy it in a forum post.

No problem, this is fine.

**Comment by JungleJim42** [comment]
Here is the .cue file:
REM GENRE "Progressive Rock"
PERFORMER "Pink Floyd"
TITLE "The Dark Side Of The Moon"
FILE "James Guthrie Surround Mix (2003).flac" WAVE
  TRACK 01 AUDIO
    TITLE "Speak To Me"
    PERFORMER "Pink Floyd"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Breathe (In The Air)"
    PERFORMER "Pink Floyd"
    INDEX 01 01:00:67
  TRACK 03 AUDIO
    TITLE "On The Run"
    PERFORMER "Pink Floyd"
    INDEX 01 03:51:84
  TRACK 04 AUDIO
    TITLE "Time"
    PERFORMER "Pink Floyd"
    INDEX 01 07:25:25
  TRACK 05 AUDIO
    TITLE "The Great Gig In The Sky"
    PERFORMER "Pink Floyd"
    INDEX 01 14:32:88
  TRACK 06 AUDIO
    TITLE "Money"
    PERFORMER "Pink Floyd"
    INDEX 01 19:05:00
  TRACK 07 AUDIO
    TITLE "Us & Them"
    PERFORMER "Pink Floyd"
    INDEX 01 25:51:34
  TRACK 08 AUDIO
    TITLE "Any Colour You Like"
    PERFORMER "Pink Floyd"
    INDEX 01 33:42:82
  TRACK 09 AUDIO
    TITLE "Brain Damage"
    PERFORMER "Pink Floyd"
    INDEX 01 37:10:22
  TRACK 10 AUDIO
    TITLE "Eclipse"
    PERFORMER "Pink Floyd"
    INDEX 01 41:02:05

**Comment by systematicat** [comment]
Can confirm this bug. Very often flacon can't see *.flac files bigger than 2.2-2.5Gb

**Comment by SokoloffA** [comment]
Confirmed, I have reproduced the bug. Your file is too big and does not fit into the WAF format header fields. I will not have to use wave64 format

**Comment by systematicat** [comment]
> Confirmed, I have reproduced the bug. Your file is too big and does not fit into the WAF format header fields. I will not have to use wave64 format

In vain... 
Whatever, I'll use unflac.

**Comment by SokoloffA** [comment]
>  I will not have to use wave64 format

Oh sorry! I was writing in the subway, and I wrote stupidity. 
I wanted to say that **I will plan to switch from WAV to WAVE64**. But it will take some time.

**Comment by systematicat** [comment]
> > I will not have to use wave64 format
> 
> Oh sorry! I was writing in the subway, and I wrote stupidity. I wanted to say that **I will plan to switch from WAV to WAVE64**. But it will take some time. 

Huge thanks to you SokoloffA!

**Comment by JungleJim42** [comment]
Thanks for looking up into this and for your time. I just sent you a little thank you on Paypal. Have a nice day!

**Comment by SokoloffA** [comment]
Guys I have good news, and problem

**Good news**
I've wrote support for large FLAC files. Since not all encoders support Wave64, I use WAV for individual tracks inside the program. But I hope it's for one track, it's not such a critical limitation.

**Problem**
I came across the fact that the metaflac does not support replaygain for multi-channel sound. I plan to show a warning in this situation. I found this topic on [hydrogenaud.io](https://hydrogenaud.io/index.php?topic=55115.0), but like the topicaster, I don't understand is this a utility problem, or a fundamental limitation.

I will be happy if someone gives me more information.

**Comment by ChaosBlades** [comment]
For those that are running into this issue and need to still get some nice vinyl rips split. I am working around this issue by using a Windows VM and running Medieval CUE Splitter. It is in the Windows Store.

**Comment by SokoloffA** [comment]
Done in master

**Comment by JungleJim42** [comment]
Hi! I am confused on how to get the new version with this correction. Using the PPA I could upgrade to version 8.1.0, but it still doesn't work (can't load large flac files). Thanks!

**Comment by SokoloffA** [comment]
I was waiting for translators, and I was doing some integration tests. I plan to release a new version today or tomorrow.
