### ISSUE TITLE
Add folder screen freezes in Debian virtual machine

### ISSUE THREAD

**Issue by Frigbog** [flacon/flacon#170]
Currently running Flacon 8.2.0 in a virtual machine on Debian 10 via Flatpak. The issue was seen in earlier versions of Flacon as well.
When I try to add a folder a folder selection window appears but there is no way you can select a folder. The window completely freezes an the only thing you can do is kill the application. 
This behavior is not seen in a physical machine running Debian 11, it's working well in this setup.
Is there anything that can be done to troubleshoot the issue?

**Comment by SokoloffA** [comment]
Flatpack turned out to be a rather problematic format. Perhaps your problem is described in [the issue](https://github.com/flatpak/flatpak/issues/3462).
Often problems with Flatpack are solved by granting [full access to the disk](https://davejansen.com/give-full-filesystem-access-to-flatpak-installed-applications/). Please, try it and write it helped or not.

P.S.
I'll try to reproduce your problem.

**Comment by Frigbog** [comment]
The issue seems to be reproducible. I installed a new vm with Debian 10.11 and KDE, the same problem occurs. Granting Flacon full access to the file system does not solve the problem. 
System:
Debian 10.11      kernel release 4.19.0-18-amd64
KDE Plasma 5.14.5
KDE Frameworks 5.54.0
Flatpak 1.2.5

As mentioned before, it works on a Debian 11 system. I cannot upgrade the Debian 10 system due to other application  dependencies.

**Comment by SokoloffA** [comment]
I'm an idiot, instead of "Add folder" I checked "Add disc". After I read your message carefully I was able to reproduce the problem.

I done some tests:
* I installed Debian 10 + KDE in the VirtualBox
* Build flatpak-portal-test-de (see instructions on https://invent.kde.org/libraries/xdg-portal-test-kde/-/tree/master)
* Run `flatpak run org.kde.portal-test-kde`
* As result "Open directory (modal)" dialog freezes 

So it's not a bug in the Flacon, it's a bug in Flatpak runtime. I also found a[ message about such a problem](https://www.mail-archive.com/kde-bugs-dist@kde.org/msg576754.html)

P.S.
I am currently installing Debian 11 to test on it

**Comment by Frigbog** [comment]
OK thanks for the feedback. I guess we'ĺl have to hope this will be fixed in flatpak someday. Flacon version 6.1.0-1 can be installed on Debian 10 natively. Can you recommend using this version? Are there any differences between both versions of Flacon, i.e. in quality of the converted files?

**Comment by Frigbog** [comment]
I noticed you put up Flacon version 8.3.0 in your repo. I upgraded and everything is working now! It must definitely have something to do with flatpak.

**Comment by SokoloffA** [comment]
> I upgraded and everything is working now! 

Have you updated Falcon or have you updated Debian?

**Comment by Frigbog** [comment]
On Debian 10: I uninstalled the flatpak version of Flacon. I had already configured the Flacon repo list (for earlier versions of Flacon). Then I upgraded the Debian system and I noticed there was a new Flacon version available. So I installed this directly on the local file system and itś working.
